### ISSUE TITLE
Frog svg for Gab

### ISSUE THREAD

**Issue by acalvino4** [vinyanalista/font-awesome-gab-parler#1]
Feature Request: It would be really nice to have the frog gab icon available in this library as well!

**Comment by vinyanalista** [comment]
This one? https://commons.wikimedia.org/wiki/File:Gab_Logo.svg

**Comment by vinyanalista** [comment]
@acalvino4 I did it:

![image](https://user-images.githubusercontent.com/1576506/113521884-c2168c00-9572-11eb-8506-281e77876ea1.png)

I'm moving all my work to GitLab. New URLs are:

- Repo: https://gitlab.com/antoniomedeiros/font-awesome-gab-parler
- Website: so far, https://antoniomedeiros.gitlab.io/font-awesome-gab-parler/ (but I'm trying to move it to https://antoniomedeiros.dev/font-awesome-gab-parler/)

**Comment by acalvino4** [comment]
thanks!
